# Generated by Django 5.1.1 on 2024-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroku',
            name='age',
            field=models.IntegerField(default=24, verbose_name='年齢を教えてくれるかな'),
        ),
    ]
