# Generated by Django 5.1.1 on 2024-09-23 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_goroku_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroku',
            name='author',
            field=models.CharField(default='野獣先輩', max_length=30, verbose_name='人物'),
        ),
        migrations.AddField(
            model_name='goroku',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='goroku',
            name='goroku',
            field=models.CharField(default='やりますねぇ！', max_length=200, verbose_name='語録'),
        ),
    ]
